"""add_level_xp_vitality

Revision ID: a11972cd226d
Revises: 68184d7b2fdf
Create Date: 2026-03-31 11:19:12.406523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11972cd226d'
down_revision: Union[str, Sequence[str], None] = '68184d7b2fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('category_scores', sa.Column('level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('category_scores', sa.Column('xp', sa.Float(), server_default='0', nullable=False))
    op.add_column('category_scores', sa.Column('xp_to_next', sa.Float(), server_default='10', nullable=False))
    op.add_column('category_scores', sa.Column('vitality', sa.Float(), server_default='50', nullable=False))
    op.drop_column('category_scores', 'score')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_scores', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('category_scores', 'vitality')
    op.drop_column('category_scores', 'xp_to_next')
    op.drop_column('category_scores', 'xp')
    op.drop_column('category_scores', 'level')
    # ### end Alembic commands ###
